build:
	@spm build

deploy:
	@rm -rf sea-modules/ucloud/backbone-pageable
	@mkdir  sea-modules/ucloud/backbone-pageable
	@mkdir  sea-modules/ucloud/backbone-pageable/1.3.2
	@cp     dist/*.* sea-modules/ucloud/backbone-pageable/1.3.2
	@echo
	@echo   " deploy to seajs-modules/ucloud/backbone-pageable/1.3.2"
	@echo
