build:
	@spm build

deploy:
	@rm	-rf /data/home/wentianle/uwebsite/static/js/ucloud/sea-modules/ucloud/plugins/1.3.1
	@mkdir	/data/home/wentianle/uwebsite/static/js/ucloud/sea-modules/ucloud/plugins/1.3.1
	@cp	dist/*.* ~/uwebsite/static/js/ucloud/sea-modules/ucloud/plugins/1.3.1
	@echo	" deploy to ~/uwebsite/static/js/ucloud/sea-modules/ucloud/plubins/1.3.1
